version: '3.8'

services:
  # Next.js application
  app:
    container_name: lumen-adtech-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: always
    networks:
      - lumen-network

  # PostgreSQL database
  postgres:
    container_name: lumen-adtech-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-lumen_adtech}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - lumen-network

  redis:
    container_name: lumen-adtech-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-password}
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - lumen-network

  # PgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@lumen-adtech.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  pgadmin_data:

networks:
  lumen-network:
    driver: bridge 